<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
Schema::create('roles', fn(Blueprint $t)=>[$t->id(),$t->string('name')->unique(),$t->string('guard_name')->default('web'),$t->timestamps()]);
Schema::create('permissions', fn(Blueprint $t)=>[$t->id(),$t->string('name')->unique(),$t->string('guard_name')->default('web'),$t->timestamps()]);
Schema::create('role_has_permissions', fn(Blueprint $t)=>[$t->foreignId('permission_id')->constrained()->cascadeOnDelete(),$t->foreignId('role_id')->constrained()->cascadeOnDelete(),$t->primary(['permission_id','role_id'])]);
Schema::create('model_has_roles', fn(Blueprint $t)=>[$t->foreignId('role_id')->constrained()->cascadeOnDelete(),$t->string('model_type'),$t->unsignedBigInteger('model_id'),$t->index(['model_id','model_type']),$t->primary(['role_id','model_id','model_type'],'model_has_roles_pk')]);
Schema::create('model_has_permissions', fn(Blueprint $t)=>[$t->foreignId('permission_id')->constrained()->cascadeOnDelete(),$t->string('model_type'),$t->unsignedBigInteger('model_id'),$t->index(['model_id','model_type']),$t->primary(['permission_id','model_id','model_type'],'model_has_permissions_pk')]);
foreach(['regions','nationalities','currencies','languages'] as $table){ Schema::create($table, fn(Blueprint $t)=>[$t->id(),$t->string('name'),$t->string('code')->nullable(),$t->string('status')->default('active'),$t->timestamps()]); }
Schema::create('branches', fn(Blueprint $t)=>[$t->id(),$t->foreignId('region_id')->nullable()->constrained()->nullOnDelete(),$t->string('name'),$t->string('code')->nullable(),$t->string('email')->nullable(),$t->string('phone')->nullable(),$t->text('address')->nullable(),$t->string('status')->default('active'),$t->timestamps()]);
Schema::create('locations', fn(Blueprint $t)=>[$t->id(),$t->foreignId('region_id')->nullable()->constrained()->nullOnDelete(),$t->string('name'),$t->string('code')->nullable(),$t->string('status')->default('active'),$t->timestamps()]);
Schema::create('company_settings', fn(Blueprint $t)=>[$t->id(),$t->string('company_name'),$t->string('logo')->nullable(),$t->string('email')->nullable(),$t->string('phone')->nullable(),$t->foreignId('currency_id')->nullable()->constrained()->nullOnDelete(),$t->string('timezone')->default('UTC'),$t->foreignId('language_id')->nullable()->constrained()->nullOnDelete(),$t->timestamps()]);
Schema::create('activity_log', fn(Blueprint $t)=>[$t->id(),$t->string('log_name')->nullable(),$t->text('description'),$t->nullableMorphs('subject'),$t->nullableMorphs('causer'),$t->json('properties')->nullable(),$t->string('event')->nullable(),$t->timestamps()]);
} public function down(): void { foreach(['activity_log','company_settings','locations','branches','languages','currencies','nationalities','regions','model_has_permissions','model_has_roles','role_has_permissions','permissions','roles'] as $t) Schema::dropIfExists($t); } };
