<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
Schema::create('agents', fn(Blueprint $t)=>[$t->id(),$t->string('name'),$t->string('company'),$t->decimal('credit_balance',12,2)->default(0),$t->foreignId('currency_id')->nullable()->constrained()->nullOnDelete(),$t->string('contact')->nullable(),$t->string('email')->nullable(),$t->string('status')->default('active'),$t->timestamps(),$t->index(['status','company'])]);
Schema::create('agent_route_assignments', fn(Blueprint $t)=>[$t->id(),$t->foreignId('agent_id')->constrained()->cascadeOnDelete(),$t->foreignId('travel_route_id')->constrained()->cascadeOnDelete(),$t->unsignedInteger('seat_quota')->default(0),$t->unsignedInteger('daily_limit')->default(0),$t->decimal('price',10,2)->nullable(),$t->string('status')->default('active'),$t->timestamps(),$t->unique(['agent_id','travel_route_id']),$t->index(['travel_route_id','status'])]);
Schema::create('agent_seat_allocations', fn(Blueprint $t)=>[$t->id(),$t->foreignId('agent_id')->constrained()->cascadeOnDelete(),$t->foreignId('travel_schedule_id')->constrained()->cascadeOnDelete(),$t->unsignedInteger('allocated_seats'),$t->unsignedInteger('used_seats')->default(0),$t->date('allocation_date'),$t->string('status')->default('active'),$t->timestamps(),$t->unique(['agent_id','travel_schedule_id']),$t->index(['allocation_date','status'])]);
Schema::create('agent_wallet_transactions', fn(Blueprint $t)=>[$t->id(),$t->foreignId('agent_id')->constrained()->cascadeOnDelete(),$t->foreignId('booking_id')->nullable()->constrained()->nullOnDelete(),$t->string('type'),$t->decimal('amount',12,2),$t->decimal('balance_after',12,2),$t->text('description')->nullable(),$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(),$t->timestamps(),$t->index(['agent_id','type','created_at'])]);
Schema::table('bookings', fn(Blueprint $t)=>[$t->foreignId('agent_id')->nullable()->after('created_by')->constrained()->nullOnDelete(),$t->index(['agent_id','status','travel_date'])]);
Schema::create('check_ins', fn(Blueprint $t)=>[$t->id(),$t->foreignId('booking_id')->constrained()->cascadeOnDelete(),$t->foreignId('passenger_id')->constrained()->cascadeOnDelete(),$t->foreignId('travel_schedule_id')->constrained()->cascadeOnDelete(),$t->foreignId('checked_in_by')->nullable()->constrained('users')->nullOnDelete(),$t->dateTime('checked_in_at'),$t->decimal('exit_fee',10,2)->default(0),$t->string('method')->default('manual'),$t->string('status')->default('checked_in'),$t->timestamps(),$t->unique(['booking_id','travel_schedule_id']),$t->index(['travel_schedule_id','checked_in_at'])]);
Schema::create('media_assets', fn(Blueprint $t)=>[$t->id(),$t->nullableMorphs('mediable'),$t->string('collection'),$t->string('disk')->default('public'),$t->string('path'),$t->string('original_name'),$t->string('mime_type')->nullable(),$t->unsignedBigInteger('size')->default(0),$t->foreignId('uploaded_by')->nullable()->constrained('users')->nullOnDelete(),$t->timestamps(),$t->index(['collection','created_at'])]);
Schema::create('system_settings', fn(Blueprint $t)=>[$t->id(),$t->string('group'),$t->string('key'),$t->text('value')->nullable(),$t->string('type')->default('string'),$t->timestamps(),$t->unique(['group','key'])]);
Schema::create('notifications', fn(Blueprint $t)=>[$t->uuid('id')->primary(),$t->string('type'),$t->morphs('notifiable'),$t->text('data'),$t->timestamp('read_at')->nullable(),$t->timestamps()]);
Schema::create('personal_access_tokens', fn(Blueprint $t)=>[$t->id(),$t->morphs('tokenable'),$t->string('name'),$t->string('token',64)->unique(),$t->text('abilities')->nullable(),$t->timestamp('last_used_at')->nullable(),$t->timestamp('expires_at')->nullable(),$t->timestamps()]);
foreach(['travel_schedules','bookings','passengers'] as $table){ Schema::table($table, fn(Blueprint $t)=>$t->index('created_at')); }
} public function down(): void { Schema::dropIfExists('personal_access_tokens'); Schema::dropIfExists('notifications'); Schema::dropIfExists('system_settings'); Schema::dropIfExists('media_assets'); Schema::dropIfExists('check_ins'); if(Schema::hasColumn('bookings','agent_id')) Schema::table('bookings', fn(Blueprint $t)=>$t->dropConstrainedForeignId('agent_id')); Schema::dropIfExists('agent_wallet_transactions'); Schema::dropIfExists('agent_seat_allocations'); Schema::dropIfExists('agent_route_assignments'); Schema::dropIfExists('agents'); } };
