<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
Schema::create('travel_routes', fn(Blueprint $t)=>[$t->id(),$t->string('name'),$t->foreignId('origin_location_id')->constrained('locations')->cascadeOnDelete(),$t->foreignId('destination_location_id')->constrained('locations')->cascadeOnDelete(),$t->unsignedInteger('estimated_minutes')->default(0),$t->string('status')->default('active'),$t->timestamps()]);
Schema::create('route_stops', fn(Blueprint $t)=>[$t->id(),$t->foreignId('travel_route_id')->constrained()->cascadeOnDelete(),$t->foreignId('location_id')->constrained()->cascadeOnDelete(),$t->unsignedInteger('stop_order'),$t->unsignedInteger('arrival_offset_minutes')->default(0),$t->unsignedInteger('departure_offset_minutes')->default(0),$t->timestamps(),$t->unique(['travel_route_id','stop_order'])]);
Schema::create('route_charges', fn(Blueprint $t)=>[$t->id(),$t->foreignId('travel_route_id')->constrained()->cascadeOnDelete(),$t->string('name'),$t->decimal('amount',10,2),$t->string('type')->default('fare'),$t->timestamps()]);
Schema::create('seat_layouts', fn(Blueprint $t)=>[$t->id(),$t->string('name'),$t->unsignedInteger('rows'),$t->unsignedInteger('columns'),$t->string('status')->default('active'),$t->timestamps()]);
Schema::create('seats', fn(Blueprint $t)=>[$t->id(),$t->foreignId('seat_layout_id')->constrained()->cascadeOnDelete(),$t->string('seat_number'),$t->unsignedInteger('row_number'),$t->unsignedInteger('column_number'),$t->string('type')->default('standard'),$t->boolean('is_blocked')->default(false),$t->timestamps(),$t->unique(['seat_layout_id','seat_number'])]);
Schema::create('travel_schedules', fn(Blueprint $t)=>[$t->id(),$t->foreignId('travel_route_id')->constrained()->cascadeOnDelete(),$t->foreignId('seat_layout_id')->constrained()->restrictOnDelete(),$t->dateTime('departure_at'),$t->dateTime('arrival_at')->nullable(),$t->decimal('base_fare',10,2)->default(0),$t->string('status')->default('scheduled'),$t->timestamps()]);
Schema::create('passengers', fn(Blueprint $t)=>[$t->id(),$t->string('first_name'),$t->string('last_name'),$t->string('gender'),$t->date('dob')->nullable(),$t->foreignId('nationality_id')->nullable()->constrained()->nullOnDelete(),$t->string('passport')->nullable(),$t->string('national_id')->nullable(),$t->string('contact_number'),$t->timestamps()]);
Schema::create('bookings', fn(Blueprint $t)=>[$t->id(),$t->string('pnr')->unique(),$t->foreignId('passenger_id')->constrained()->cascadeOnDelete(),$t->foreignId('travel_route_id')->constrained()->cascadeOnDelete(),$t->foreignId('travel_schedule_id')->constrained()->cascadeOnDelete(),$t->foreignId('return_schedule_id')->nullable()->constrained('travel_schedules')->nullOnDelete(),$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(),$t->date('travel_date'),$t->date('return_date')->nullable(),$t->string('status')->default('confirmed'),$t->decimal('total_amount',10,2)->default(0),$t->text('qr_code')->nullable(),$t->timestamps()]);
Schema::create('booking_seat', fn(Blueprint $t)=>[$t->id(),$t->foreignId('booking_id')->constrained()->cascadeOnDelete(),$t->foreignId('seat_id')->constrained()->cascadeOnDelete(),$t->foreignId('travel_schedule_id')->constrained()->cascadeOnDelete(),$t->timestamps(),$t->unique(['seat_id','travel_schedule_id'])]);
Schema::create('seat_holds', fn(Blueprint $t)=>[$t->id(),$t->foreignId('travel_schedule_id')->constrained()->cascadeOnDelete(),$t->foreignId('seat_id')->constrained()->cascadeOnDelete(),$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete(),$t->string('token'),$t->dateTime('expires_at'),$t->timestamps(),$t->unique(['travel_schedule_id','seat_id'])]);
} public function down(): void { foreach(['seat_holds','booking_seat','bookings','passengers','travel_schedules','seats','seat_layouts','route_charges','route_stops','travel_routes'] as $t) Schema::dropIfExists($t); } };
